name: Build and Deploy to GitHub Pages (manual)

on:
  # Disabled automatic runs to avoid conflicts with SSR/Vercel deploy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: depth-site
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: depth-site/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build (static export)
        run: NEXT_EXPORT=true npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: depth-site/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


